apiVersion: v1
kind: Service
metadata:
  name: service-bodybuilder-protien
spec:
  selector:
    app: app-protien
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
#      nodePort: 30012